apiVersion: v1
kind: Service
metadata:
  name: mytime-steward
spec:
  selector:
    app: mytime
    component: steward
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: mytime-audiosocket
spec:
  selector:
    app: mytime
    component: dojo
  ports:
  - protocol: TCP
    port: 9092
    targetPort: 9092
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: mytime-voip
spec:
  selector:
    app: mytime
    component: asterisk
  ports:
  - name: sip
    protocol: UDP
    port: 5060
    targetPort: 5060
  - name: rtp
    protocol: UDP
    port: 10000
    targetPort: 10000
  type: LoadBalancer
